### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#14]
I created an analytics account. here is the code

```
 <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-EZ555D7QSW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EZ555D7QSW');
 </script>
```

it says, Copy and paste this code as the first item into the <head> of every webpage you want to measure. 
which pages are those?

**Comment by SanliFaez** [comment]
I added this code to the base.html after </head>

**Comment by aquilesC** [comment]
This will definitely shape the privacy policy of the website and we will need to add the opt-out for the tracking and the cookie banner. Nor sure we are ready for that in such a short term.

**Comment by SanliFaez** [comment]
what we take example over from cyberpoli. they only explain the term of google analytics in their [privacy statement](https://www.cyberpoli.nl/info/privacy)? if changes to privacy policy is sufficient, we are almost ready to add those. @JoselineHouwman has adapted the text from cyberpoli.

is there any analytics tags other than google that does not require cookies statement?
what if we use privalytics like you do in PFTL?

**Comment by aquilesC** [comment]
Privalytics is my own toy project. I'm happy to give access, but I'm not sure it can be a long-term solution (I can't guarantee I'll maintain the website years to come).  

Other, more mature options are: 

https://plausible.io/
https://simpleanalytics.com/ <- This one is Dutch
https://usefathom.com/
https://matomo.org 

I believe there are ways of anonymizing google analytics and removing the cookie, but that goes beyond my current knowledge

**Comment by SanliFaez** [comment]
apparently, but anonymizing IP addresses, we do not need consent.
[here is a guide](https://www.datadrivenu.com/gdpr-ip-addresses-google-analytics/)

do you agree @aquilesC with this solution?
shall I follow these steps and are we then okay for the moment without any pop-up?

**Comment by aquilesC** [comment]
For what I could quickly gather, seems like a good way to proceed. So if
can follow the guide and make a pull request I'll merge it.

**Comment by SanliFaez** [comment]
I am adding this line to the tracker tag
`  gtag('config', 'G-EZ555D7QSW', { 'anonymize_ip': true });`

this should be enough as far as I have understood.
