### ISSUE TITLE
Text issues for hard-code parts

### ISSUE THREAD

**Issue by JoselineHouwman** [Klimaat-Helpdesk/website#2]
Here is a known issues about static texts that will be updated. please add any other words or sentences that you spot to the comments and I will list them here

- [x] "Wie we zijn" -> "Wie zijn wij?"

- [x] Jullie meest gestelde vragen" -> "Jullie meestgestelde vragen"

- [x]  "De bronnen worden onderzocht en worden door 2 experts nagekeken. De wachttijd voor ieder antwoord kan 1 maand duren." -> De vraag wordt doorgestuurd naar een expert, die aan de hand van verschillende bronnen een antwoord schrijft. Dit antwoord wordt door een tweede expert nagekeken en wordt dan als artikel gepubliceerd op de website [lees verder]

- [x]  "Het climaat-helpdesk bestaat uit wetenschappelijke klimaatexperts uit 10 van de 14 nederlandse universiteiten. Wij zijn een onafhankelijke stichting..." -> Elke vraag wordt beantwoord door een actieve wetenschapper of deskundige die expert is op dat vakgebied

- [x]  "Our terms and conditions" -> Ik heb de algemene voorwaarden gelezen en ga er mee akkoord.

- [x]  "Als je wilt, kun je hier je emailadres achterlaten om op de hoogte gehouden te worden." -> Laat je mailadres achter als je op de hoogte gehouden wilt worden [optioneel]

- [x]  In footer: "scientists for future" -> "Scientists4Future NL"

- [x]  In question form: there is a part that also mentioned 4 weeks, needs correction.

- [x] On top of experts page, add a short description : "Onze experts zijn in Nederland werkzaam bij kennisinstellingen, zoals PBL, en/of als onderzoekers bij universiteiten, hogescholen, of instituten, bijvoorbeeld KNMI. Elke vraag wordt, aan de hand van het vakgebied, beantwoord door één of meerdere experts. "

- [x]  https://www.klimaathelpdesk.org/answers/ should be https://www.klimaathelpdesk.org/vragen/. Changing the slug breaks the menu.

- [x] Redirect the terms link when submitting a question

**Comment by JoselineHouwman** [comment]
Copied from https://gitlab.com/s4fnl/climate-facts/-/issues/100

**Comment by aquilesC** [comment]
>  https://www.klimaathelpdesk.org/answers/ should be https://www.klimaathelpdesk.org/vragen/. Changing the slug breaks the menu.

This can be solved directly from the CMS here: 
https://www.klimaathelpdesk.org/cms/wagtailmenus/mainmenu/edit/1/

> On top of experts page, add a short description : "Onze experts zijn in Nederland werkzaam bij kennisinstellingen, zoals PBL, en/of als onderzoekers bij universiteiten, hogescholen, of instituten, bijvoorbeeld KNMI. Elke vraag wordt, aan de hand van het vakgebied, beantwoord door één of meerdere experts. "

This can be solved by editing this page (add an Intro to show text above and an outro to show text below the list):

https://www.klimaathelpdesk.org/cms/pages/5/edit/

---

For the issues on the text in the template, the best is to search for whatever must be changed, for example here: 

https://github.com/Klimaat-Helpdesk/website/search?q=hoogte+gehouden+te+worden

Go to the file with ``html`` extension (don't change the ``.po`` files), change whatever must be changed in the text, and create a pull request:

![pull_request_screenshot](https://user-images.githubusercontent.com/2494344/96839423-78fdd000-1449-11eb-82f4-5839a9111327.png)

I will be able to review the changes and approve them. 

If you reference this issue when creating the pull request, it'll make the tracking of the changes easier in the short-term

**Comment by SanliFaez** [comment]
I am changing the small edits in a new branch (called small edits). I will mention changes and issues numbers in the commit message.

**Comment by Arfor** [comment]
@aquilesC what Daan meant was that if you change the slug from answers -> vragen, it breaks the menu (those hrefs are hardcoded in the html).
The change has been made in the cms and I've made a pull request with the necessary changes in the htmls.

**Comment by JoselineHouwman** [comment]
When submitting a Question and clicking on the terms, the page still directs to www.klimaathelpdesk.org/terms/ (which does not exist. Please redirect to www.klimaathelpdesk.org/voorwaarden/
