### ISSUE TITLE
grammer errors on front page

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#21]
two points:

we is achter --> Wie zijn de mensen achter de KlimaatHelpdesk
button text --> Meer lezen over ons

**Comment by nieske** [comment]
Additional spelling error: on the experts page, it says 'consultents' under Jan Paul van Soest, which should be 'consultants'.

**Comment by aquilesC** [comment]
@nieske , those mistakes can be corrected from the cms (i.e. they are not part of the code of the website, therefore any editor has the power to quickly modify them)

**Comment by SanliFaez** [comment]
fixed it to "consultants"
