### ISSUE TITLE
Can't submit question without email address

### ISSUE THREAD

**Issue by nieske** [Klimaat-Helpdesk/website#22]
When submitting a question, the text says that leaving your email address is optional. However, it is impossible to submit the form when you don't fill in an email address.
![Schermafbeelding 2020-10-27 om 11 25 13](https://user-images.githubusercontent.com/5729823/97289155-1b052a00-1847-11eb-82e2-d489b1e0c439.png)

**Comment by SanliFaez** [comment]
one can submit a question by just putting -, only the field should not be left empty. 
It is confusing I know and I think this should be fixed, but I could not figure out a quick solution.

**Comment by nieske** [comment]
Wouldn't it be possible to change the field properties so that it is no longer mandatory?
Otherwise, it should be mentioned in the text. Something like "Als je je mailadres liever niet achterlaat, vul dan 'nee' in." A bit clunky but at least it's clearer than the current situation.

**Comment by aquilesC** [comment]
This is uncanny, the e-mail is marked as optional [here](https://github.com/Klimaat-Helpdesk/website/blob/63c6edf12cd5f2e09c97d4a0bbdcd8d0833f35bd/klimaat_helpdesk/core/models.py#L16) not sure what is going on

**Comment by aquilesC** [comment]
Found the source of the problem, is [here](https://github.com/Klimaat-Helpdesk/website/blob/63c6edf12cd5f2e09c97d4a0bbdcd8d0833f35bd/klimaat_helpdesk/core/forms.py#L30)
