### ISSUE TITLE
Error 500 when trying to approve an incoming question

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#24]
I recieve this error message for approving a question of 27 october. I have not encountered this before, can it be because of the special characters or is it something new?

```

Ooops!!! 500
Looks like something went wrong!

We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

```

**Comment by aquilesC** [comment]
I just approved a question with no problems, so no idea

**Comment by aquilesC** [comment]
Should be solved, could you try again?

**Comment by SanliFaez** [comment]
indeed I can approve with no problem.
