### ISSUE TITLE
Double tags under experts

### ISSUE THREAD

**Issue by Arfor** [Klimaat-Helpdesk/website#34]
It seems as if the category of an answer provided by an expert is added to the respective profile. If the expert gives two answers within the same category, they get a double tag. 

This happens for example with [Anne-Jo Visser](https://www.klimaathelpdesk.org/experts/#13) and [Eric Lambert](https://www.klimaathelpdesk.org/experts/#17).

**Comment by aquilesC** [comment]
This is happening in this line: 

https://github.com/Klimaat-Helpdesk/website/blob/0af7dc0dc16be5c53053e4b3c4b86a0d9706b898/klimaat_helpdesk/experts/models.py#L52

It is appending categories to a list carelessly without looking for duplicates. Can be solved using a set instead.
