### ISSUE TITLE
Labels on homepage

### ISSUE THREAD

**Issue by JoselineHouwman** [Klimaat-Helpdesk/website#4]
Is it possible to apply the filters on-click instead of having to press "apply filters"? The black colouring when it is selected is a good indicator already that it should be active.
![afbeelding](https://user-images.githubusercontent.com/63670085/96766556-8e3c1580-13db-11eb-84e8-1c653bc72239.png)

**Comment by aquilesC** [comment]
It is possible but beyond my time-availability. I've put it as a to-do for the next iteration of the website.
