### ISSUE TITLE
'Contact' menu difficult to find

### ISSUE THREAD

**Issue by arthuroldeman** [Klimaat-Helpdesk/website#45]
'Contact' is currently only to be found in the bottom menu of the website. When the browser has a certain width, 'Contact' falls underneath 'Een initiatief van...' and becomes a bit difficult to spot. Can be fixed by putting 'Over ons' and 'Contact' on a different line?
Another suggestion is to also put 'Contact' (and also 'Over ons'..?) in the main menu that pops up from the top right, to increase visibility.

**Comment by aquilesC** [comment]
I have added the 'contact' to the menu, could you check on the website? Also, is 'contact' the way to say it in Dutch?

**Comment by arthuroldeman** [comment]
I can see it on the website menu, and works fine! Contact is the correct way of putting in it Dutch, yeah. Great!
