### ISSUE TITLE
Front pages categories under experts

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#53]
Under the list of categories for the expert Peter Kuipers Munneke, both fields are the same. why?
<img width="450" alt="Screenshot 2020-11-03 at 21 46 51" src="https://user-images.githubusercontent.com/5281249/98038867-1c71bc00-1e1e-11eb-966c-99329f1fd664.png">

**Comment by aquilesC** [comment]
Duplicate of #34 , closing
