### ISSUE TITLE
images do not automatically feature on twitter

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#62]
I tried to post an article with images on twitter, but it did not automatically feature any of those. can this be adjusted in formatting the template?

**Comment by aquilesC** [comment]
I tried already, and I'm not sure it is Twitter not indexing the website
somehow or a badly configured template. What happens on other networks,
such as Facebook?

Ideally, each answer should set a shareable image, or use a default (like
the logo) if there's no image defined. Would that make sense?

It would require an extra step for the person creating the article online
though.


https://www.aquicarattino.com

This message was sent from a mobile device. Excuse the brevity and possible
mistakes.
