### ISSUE TITLE
Quotes cut off words from text

### ISSUE THREAD

**Issue by Arfor** [Klimaat-Helpdesk/website#64]
When you insert a quote in wagtail, it's container cuts off the previous sentence. 
![afbeelding](https://user-images.githubusercontent.com/37039019/98834373-6b7fa880-243f-11eb-80b0-f36056e4acd9.png)

Maybe can be fixed by lowering the z-index of the div container or by making it transparent?

**Comment by Arfor** [comment]
Oke, really easy fix is just to add a blank line in the cms in the rich text _before_ the quote.

**Comment by aquilesC** [comment]
It's good you found a quick fix for this! In any case, let's keep this issue open since it is something that must be addressed even if not urgently.
