### ISSUE TITLE
Sources on website not ordered as in CMS

### ISSUE THREAD

**Issue by Arfor** [Klimaat-Helpdesk/website#66]
[Example on website](https://www.klimaathelpdesk.org/answers/zijn-er-niet-gewoon-te-veel-mensen-op-aarde/)

![afbeelding](https://user-images.githubusercontent.com/37039019/99085528-96e1cf00-25c8-11eb-9102-04b806470a35.png)
vs
![afbeelding](https://user-images.githubusercontent.com/37039019/99085570-a6f9ae80-25c8-11eb-953d-b735ae5c18b8.png)

**Comment by aquilesC** [comment]
Indeed, apparently this was by design from Fabrique, this is what must be changed:

https://github.com/Klimaat-Helpdesk/website/blob/b08a178298fc6fcf691a2b6905ca36b2810cf741/klimaat_helpdesk/cms/models.py#L200
