### ISSUE TITLE
Padding before quote block masks content

### ISSUE THREAD

**Issue by daanreijnders** [Klimaat-Helpdesk/website#68]
See https://www.klimaathelpdesk.org/answers/waarom-vallen-economische-zaken-en-klimaat-onder-1-ministerie/. The paragraph before the first quote block is partially hidden by whitespace. Can the amount of whitespace be reduced so that it doesn't mask content?

<img width="948" alt="Screen Shot 2020-11-15 at 15 28 08" src="https://user-images.githubusercontent.com/9340879/99187486-3765f980-2757-11eb-8321-adba0a33a5b8.png">

**Comment by aquilesC** [comment]
Duplicated of #64 , therefore closing. Feel free to reopen if not duplicated.
