### ISSUE TITLE
order of question on the frontpage

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#7]
it seems to be static, while it claims to be most frequently asked. this should be clarified

**Comment by aquilesC** [comment]
The order can be set in the backend:

![sort_screenshot](https://user-images.githubusercontent.com/2494344/96836990-03443500-1446-11eb-89e3-9fee3ed2a3fe.png)

Questions must be sorted manually by editors

**Comment by SanliFaez** [comment]
this sorting does not seem to apply the same to how the list is compiled on the website. For the experts, there is no list in the backend page.

**Comment by aquilesC** [comment]
This is not about the experts, but about the answers, experts are discussed in #6 

If you do click in sort, you'll see that the ordering of the answers is the same than the one on the homepage and you can move them around.

**Comment by SanliFaez** [comment]
yes I saw that. this controls the order on the complete list. the order of answers on the front page is a different issue and seems to be checking the "feature in front page" tick-box. I am changing more frequent to "recent" to avoid making a false claim.

**Comment by aquilesC** [comment]
Is this then addressed in the pull request #9 ?

**Comment by SanliFaez** [comment]
yes, it should be.
