### ISSUE TITLE
Wrong font 'Experts' page

### ISSUE THREAD

**Issue by daanreijnders** [Klimaat-Helpdesk/website#71]
On the [experts](https://www.klimaathelpdesk.org/experts/) page, the introduction is rendered in the incorrect font.

**Comment by aquilesC** [comment]
This is because the text was copy/pasted with that specific font into the rich text editor, not a bug of the website itself. Can be edited within the CMS.

**Comment by daanreijnders** [comment]
Newly added text on that page also doesn't format well (I checked it through a page preview). Moreover, there is no option in the CMS to remove markup from text. So both copy-pasting the text and writing the text from scratch cause the text on that page to be wrongly formatted.

**Comment by aquilesC** [comment]
Could you describe what were you expecting to get, and what you got?

**Comment by daanreijnders** [comment]
![Screenshot 2020-12-11 at 10 57 11](https://user-images.githubusercontent.com/9340879/101889724-0b943300-3ba0-11eb-9218-83b782a821bd.png)

**Comment by daanreijnders** [comment]
Thanks for fixing this!
