### ISSUE TITLE
#CO2 - make subscript possible also in headings

### ISSUE THREAD

**Issue by huberma** [Klimaat-Helpdesk/website#77]
In the richtext it is already possible to have subscript eg for CO2, but not yet for headings

**Comment by aquilesC** [comment]
It is already possible, you just need to use the proper unicode character (see [this](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts))

You can try to copy/paste the following: 

CO₂

I created a dummy article to show it works, [here](https://www.klimaathelpdesk.org/cms/pages/108/view_draft/) 

Bear in mind that the same works also for categories, I assumed using CO2 was customary in these topics (easier to google, etc.)

**Comment by aquilesC** [comment]
Just out of fun, I changed the text of the issue to see if it also works on Github, and turns, it does! ;-)

**Comment by huberma** [comment]
Perfect! Thanks :)
