### ISSUE TITLE
URGENT! the ask form give a Ooops!!! 500 problem

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#85]
in the second page of the ask form, we now get an error:
can you please check @aquilesC ?

> 
> Ooops!!! 500
> Looks like something went wrong!
> 
> We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

**Comment by aquilesC** [comment]
Solved. I got all the questions submitted, not sure how to share them, on Teams?
