### ISSUE TITLE
Homepage lacks meta description

### ISSUE THREAD

**Issue by daanreijnders** [Klimaat-Helpdesk/website#88]
The homepage currently lacks a meta description, while it's specified in the CMS at 'Helpdesk Climate Starts Here'. Is this the right place to specify it? Or should it be defined elsewhere?

The meta description that makes most sense to me is our pay-off: 'Antwoorden van wetenschappers op al je vragen over klimaatverandering'.

**Comment by aquilesC** [comment]
Do you mean it is missing from the html? Is this something you dare trying to fix? I'm willing to guide you if you don't know where to get started.

**Comment by daanreijnders** [comment]
Yup, I mean the meta description in the HTML. I'd like to give it a try. Where do you think I should start looking?

**Comment by aquilesC** [comment]
The templates that are responsible for rendering the HTML are [in this folder](https://github.com/Klimaat-Helpdesk/website/tree/main/klimaat_helpdesk/templates) 

Answers to questions do have a ``meta name="description"``, so you can get some inspiration from them to copy the structure into the home page templates. The article template is [this one](https://github.com/Klimaat-Helpdesk/website/blob/main/klimaat_helpdesk/templates/cms/answer_detail.html). Note that (in case you are curious) the ``block extra_head`` is defined in the [base.html](https://github.com/Klimaat-Helpdesk/website/blob/main/klimaat_helpdesk/templates/base.html). 

For the home page template, you can find it [here](https://github.com/Klimaat-Helpdesk/website/blob/main/klimaat_helpdesk/templates/core/home_page.html). Let me know how it goes!

**Comment by daanreijnders** [comment]
After looking into how Docker works for quite a bit, I think I managed to build the website locally. But I have no clue how to render something as simple as the homepage. I don't think I'll be able to test the fix myself locally without spending many hours more on this.

I think really all we need is adding some of the `extra_head` block into the template for the homepage. I assume the description will then be pulled from the CMS correctly. If not, we could hard-code it instead of `{{ self.excerpt }}`. 

So what I think should be added in [home_page.html](https://github.com/Klimaat-Helpdesk/website/blob/main/klimaat_helpdesk/templates/core/home_page.html) is:

```html
{% block extra_head %}
  <meta property="og:title" content="{{ self.title }}">
  <meta property="twitter:title" content="{{ self.title }}">
  {% if self.excerpt %}
    <meta name="description" content="{{ self.excerpt }}">
    <meta name="og:description" content="{{ self.excerpt }}">
    <meta name="twitter:description" content="{{ self.excerpt }}">
  {% endif %}
  <meta property="twitter:site" content="@KlimaatHelpdesk">
  <meta property="twitter:card" content="summary">
  <meta property="og:locale" content="nl_NL">
  <meta property="og:site_name" content="KlimaatHelpdesk">
{% endblock extra_head %}
```

**Comment by aquilesC** [comment]
@daanreijnders , too bad you didn't chime in earlier! Setting up docker is a bit complicated at the beginning and even if you succeed, you'll need a copy of the database to get started. 

Although your solution is appropriate, I have just seen that the home page itself does not define an excerpt and the title is set to "Helpdesk Climate Starts Here" which may not be the best. I wonder if this should be set in the CMS (i.e. can be edited by anyone) or forced on the HTML. For the time being, I'll add an extra field on the home page to define the excerpt, but this should be discussed internally at some point.
