### ISSUE TITLE
database update

### ISSUE THREAD

**Issue by SanliFaez** [Klimaat-Helpdesk/website#97]
I received this message from Heroku. I guess we can just wait for them to upgrade the database for us. right?

"""
On March 10, 2021, we announced the Heroku Redis Hobby Tier Version Deprecation. Your Redis database redis-corrugated-59691 on klimaat-helpdesk-app is running the deprecated version (5.0.12) which will not be supported after June 30, 2021.

We recommended upgrading your Redis database to the latest version supported by Heroku, which is currently 6.0.12. We perform heavy testing and validation work on all new Redis releases, including testing the upgrade procedure, and are careful to only recommend versions that we trust.

You can upgrade your Redis database to the latest default version by creating a fork on the latest version and promoting it as your active add-on. You can read more about this procedure in our Dev Center article.

If you do not take action, we will upgrade your Redis database on or after June 30, 2021.
"""

**Comment by aquilesC** [comment]
I would think that we can let it passively upgrade, we should just pay attention whether something stops working after June 30. Redis, in any case, is used for the cache, the proper database is a Postgres, so I don't expect any disruption.

**Comment by aquilesC** [comment]
I've updated Redis already, so closing.
